### ISSUE TITLE
Revamp Community Website

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis.io#86]
We need to make some pretty big changes to the website, which include, but is not limited to, the following:

- [x] Merge [Developer Handbook](https://doc.syndesis.io/) page with community website, synchronize CD/CI pipeline (#88)
- [x] Improve/update information and documentation (#97 )
- [ ] Create CI job for deploying User docs to Syndesis website (#99)
- [ ] Update screenshots on landing page & others (#94 )
- [x] Update Google Analytics to include important dates (public presentations, etc)
- [ ] Discuss possibility of removing the website blog, or replacing with a News/Announcements page (#93 )
- [ ] Improve appearance (update octocat (#45), improve mobile compatibility and desktop styling, etc) (#96 )
- [x] Update logo and favicon (#113)
- [x] Include reference repos like Kurt's quickstart examples (cc @KurtStam )

EDIT: Moving SEO updates and improvements (#95 ) to its own epic, as it is quite entailed.
